name: forge
description: Training Hub Pessoal

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados local
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.0

  # Estado
  flutter_riverpod: ^2.5.1

  # Navegação
  go_router: ^13.0.0

  # Fontes
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
